# Generated by Django 4.1 on 2023-12-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_country_city_alter_airport_closest_big_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='airplanetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['departure_time']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='crewflight',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='crew_flights', to='airport.crew'),
        ),
    ]
