# Generated by Django 4.1 on 2023-12-11 17:30

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0004_alter_airplane_options_alter_airplanetype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(null=True, upload_to=airport.models.airplane_image_file_path),
        ),
        migrations.AddField(
            model_name='airport',
            name='image',
            field=models.ImageField(null=True, upload_to=airport.models.airport_image_file_path),
        ),
    ]
