# Generated by Django 4.1 on 2023-12-12 06:57

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0005_airplane_image_airport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='crews',
            field=models.ManyToManyField(related_name='flights', through='airport.CrewFlight', to='airport.crew'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=airport.models.airplane_image_file_path),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='name',
            field=models.CharField(max_length=133, unique=True),
        ),
        migrations.AlterField(
            model_name='airplanetype',
            name='name',
            field=models.CharField(max_length=133, unique=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=airport.models.airport_image_file_path),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=133, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=83, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=83, unique=True),
        ),
    ]
