# Generated by Django 4.1 on 2023-12-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0006_flight_crews_alter_airplane_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='crews',
        ),
        migrations.AddField(
            model_name='flight',
            name='crews',
            field=models.ManyToManyField(related_name='flights', to='airport.crew'),
        ),
        migrations.DeleteModel(
            name='CrewFlight',
        ),
    ]
