# Generated by Django 4.1 on 2023-12-13 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0007_alter_flight_crews_delete_crewflight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(10)]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="flight",
            unique_together={("route", "airplane", "departure_time", "arrival_time")},
        ),
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("source", "destination")},
        ),
    ]
