version: '3.7'

services:
  web-airport:
    restart: always
    build: .
    container_name: backend_airport
    command: ["/entrypoint.sh"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    networks:
      - airport_network
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    container_name: postgres_airport
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - airport_data:/var/lib/postgresql/data/
    networks:
      - airport_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_airport
    ports:
      - "3333:80"
    env_file:
      - .env
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - airport_pgadmin_data:/var/lib/pgadmin
    networks:
      - airport_network

networks:
  airport_network:
    driver: bridge

volumes:
  airport_data:
    driver: local
  airport_pgadmin_data:
    driver: local
